# Xcode

# Build, test, and archive an Xcode workspace on macOS.

# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:

# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

 

# CI Triggerin and Batching pipeline

trigger:

batch: true

branches:

include:

- master

pr: none

name: $(customBuildNumber)

pool:

vmImage: 'macos-latest'

# Variables

variables:

- group: TreatmentTrackingVariables

- name: MajorVersion

value: 1

- name: MinorVersion

value: 0

- name: customBuildNumber

value: '$(MajorVersion).$(MinorVersion).$(date:yy)$(DayOfYear)$(rev:.r)'

steps:

# CMD Install Fortify from Blob Storage

- task: CmdLine@2

inputs:

script: |

echo hello from macOS

mkdir /tmp/fortify-sca/

curl https://blobstorageromell.blob.core.windows.net/container1/fortify-mac.zip --output /tmp/fortify-sca/fortify-mac.zip

cd /tmp/fortify-sca/

unzip fortify-mac.zip

rm -f fortify-mac.zip

chmod -R 777 /tmp/fortify-sca/*

Fortify_SCA_and_Apps_20.1.2_osx_x64.app/Contents/MacOS/installbuilder.sh --mode unattended

ln -s /tmp/fortify-sca/bin/sourceanalyzer /usr/local/bin/sourceanalyzer

ln -s /tmp/fortify-sca/bin/fortifyupdate /usr/local/bin/fortifyupdate

ln -s /tmp/fortify-sca/bin/fortifyclient /usr/local/bin/fortifyclient

sourceanalyzer -h

# Install apple 3m apple distribution public certificate.

- task: InstallAppleCertificate@2

inputs:

certSecureFile: '$(cert.3M)'

certPwd: '$(cert.password)'

keychain: 'temp'

- task: InstallAppleProvisioningProfile@1

inputs:

provisioningProfileLocation: 'secureFiles'

provProfileSecureFile: '$(appProfile)'

- task: CocoaPods@0

inputs:

forceRepoUpdate: false

- task: Xcode@5

inputs:

actions: 'build'

configuration: 'Release'

sdk: 'iphoneos'

scheme: '3MCompliance'

packageApp: true

archivePath: 'temp/TxTracking/'

signingOption: 'manual'

signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'

provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'

provisioningProfileName: '3M Treatment Tracker'